config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :orders do
    get :thanks, on: :collection
  end

  resources :item_lines

  resource :cart

  resources :items do
    resources :orders
  end

  root 'items#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :user
  has_many :item_lines
end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/models/item_line.rb
class ItemLine < ActiveRecord::Base
  belongs_to :order
  belongs_to :cart
  belongs_to :item
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :item_lines

  def price
    total = 0
    item_lines.each do |item_line|
      total += item_line.item.price * item_line.quantity
    end
    total
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :orders
  has_one :cart

  after_create do
    create_cart
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

  def show
    @total = 0
    current_user.cart.item_lines.each do |item_line|
      @total += item_line.item.price * item_line.quantity
    end
  end

  # def create
  #   @item_lines = current_user.cart.item_lines.create(item_line_params)
  #   redirect_to root_path
  # end

  # private

  #   def item_line_params
  #     params.require(:item_line).permit(:quantity, :item_id)
  #   end
end

app/controllers/item_lines_controller.rb
class ItemLinesController < ApplicationController
  before_action :authenticate_user!

  def create
    @item_lines = current_user.cart.item_lines.create(item_line_params)
    redirect_to root_path
  end

  private

    def item_line_params
      params.require(:item_line).permit(:quantity, :item_id)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    # @items = Item.joins(:orders).group("items.id").order("orders.id DESC")
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def index
    @orders = current_user.orders
  end

  def create
    @order = current_user.orders.create

    current_user.cart.item_lines.each do |item_line|
      item_line.cart = nil
      item_line.order = @order
      item_line.save
    end

    redirect_to thanks_orders_path
  end

  def thanks
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/carts/show.html.erb
<table class="table">
  <tr>
    <th>
      상품
    </th>
    <th>
      갯수
    </th>
    <th>
      가격
    </th>
  </tr>

  <% current_user.cart.item_lines.each do |item_line| %>
    <tr>
      <td> <%= item_line.item.title %> </td>    
      <td> <%= item_line.quantity %> </td>    
      <td> <%= item_line.item.price * item_line.quantity %> </td>    
    </tr>
  <% end %>

</table>

<div class="well">
  <h1> 총합 </h1>
  <p>
    <%= @total %>
  </p>

  <div class="text-right">
    <a class="btn btn-success" href="<%= orders_path %>" data-method="post">주문하기</a>  
  </div>

</div>

app/views/items/_item.html.erb
<div class="well">
  <div class="media">
    <%= link_to item, class: "pull-left" do %>
      <img class="media-object img-thumbnail" src="<%=item.image_url%>" width="200">
    <% end %>
    <div class="media-body">
      <h2 class="media-heading"> <%= item.title %> </h4>
      <h3 class="media-heading"> ₩ <%= number_to_currency item.price, format: "%n", precision: 0 %> </h3>
      <%= simple_format item.description %>        
    </div>
  </div>
</div>

app/views/items/index.html.erb
<h1> 인기 상품 </h1>
<%= render @items %>

app/views/items/show.html.erb
<%= render @item %>
<%= render 'orders/form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shopping</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <!-- Static navbar -->
  <div class="navbar navbar-default navbar-static-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">쇼핑몰</a>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li><a href="<%= items_path %>">인기 상품</a></li>
          <li><a href="<%= orders_path %>">주문목록</a></li>
          <li><a href="<%= cart_path %>">장바구니</a></li>
          <% if user_signed_in? %>
            <li><a href="<%= destroy_user_session_path%>" data-method="delete"> 로그아웃 </a></li>

          <% else %>
            <li><a href="<%= new_user_session_path %>"> 로그인 </a></li>
          <% end %>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>

  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/orders/_form.html.erb
<% #form_for [@item, @item..build], html: {class: "form-horizontal well"} do |f| %>
<%= form_for [current_user.cart.item_lines.new(item: @item)], html: {class: "form-horizontal well"} do |f| %>
  <div class="form-group">
    <%= f.label :quantity, class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= f.text_field :quantity, class: "form-control" %>      
    </div>
  </div>
  <div class="form-group hide">
    <%= f.label :item_id, class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= f.text_field :item_id, class: "form-control" %>      
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-default" %>
    </div>
  </div>
<% end %>

app/views/orders/index.html.erb
<h1> 주문 목록 </h1>

<table class="table">
  <tr>
    <th> 날짜 </th>
    <th> 가격 </th>
    <th> 상태 </th>
  </tr>

  <% @orders.each do |order| %>
    <tr>
      <td> <%= order.created_at %> </td>
      <td> <%= order.price %> </td>
      <td> <%= order.status %> </td>
    </tr>
  <% end %>

</table>

app/views/orders/thanks.html.erb
<div class="jumbotron">
  <div class="container">
    <h1> 이용해주셔서 감사합니다. </h1>
    <p>
      <a class="btn btn-primary btn-lg" href="<%= root_path %>" role="button"> 메인 화면 돌아가기 </a>
    </p>
  </div>

</div>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>